# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:08
from __future__ import unicode_literals

import backend.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20161016_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=stdimage.models.StdImageField(upload_to=backend.models.photo_path),
        ),
    ]
