# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_tags',
            field=models.ManyToManyField(related_name='followers', to='backend.Tag'),
        ),
    ]
