# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_userprofile_followed_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set([('place', 'visitor')]),
        ),
    ]
