# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20161022_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, b'---'), (1, b'*'), (2, b'**'), (3, b'***'), (4, b'****')], default=0),
        ),
    ]
