# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20161022_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_places',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='backend.Place'),
        ),
    ]
